### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/cpu/b - Missing hadoop (example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#38]
This is one of our example applications

**Comment by mkandes** [comment]
Hadoop was deployed via Spack as part of my recent deployment of Spark. See https://github.com/sdsc/spack/issues/42. However, it is not currently exposed via the lmod module environment.

```
[mkandes@login02 ~]$ module spider hadoop

----------------------------------------------------------------------------
  hadoop:
----------------------------------------------------------------------------
     Versions:
        hadoop/2.6.0
        hadoop/3.2.2

----------------------------------------------------------------------------
  For detailed information about a specific "hadoop" package (including how to load the modules) use the module's full name. Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider hadoop/3.2.2
----------------------------------------------------------------------------

 

[mkandes@login02 ~]$ module spider hadoop/2.6.0

----------------------------------------------------------------------------
  hadoop: hadoop/2.6.0
----------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "hadoop/2.6.0" module is available to load.

      cpu/0.15.4
 

 

[mkandes@login02 ~]$ module spider hadoop/3.2.2

----------------------------------------------------------------------------
  hadoop: hadoop/3.2.2
----------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "hadoop/3.2.2" module is available to load.

      cpu/0.15.4
 

 

[mkandes@login02 ~]$ module spider spark

----------------------------------------------------------------------------
  spark:
----------------------------------------------------------------------------
     Versions:
        spark/2.4.8
        spark/3.2.1
     Other possible modules matches:
        spark/3.4.0

----------------------------------------------------------------------------
  To find other possible module matches execute:

      $ module -r spider '.*spark.*'

----------------------------------------------------------------------------
  For detailed information about a specific "spark" package (including how to load the modules) use the module's full name. Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider spark/3.2.1
----------------------------------------------------------------------------
set mark: ...skipping...

----------------------------------------------------------------------------
  spark:
----------------------------------------------------------------------------
     Versions:
        spark/2.4.8
        spark/3.2.1
     Other possible modules matches:
        spark/3.4.0

----------------------------------------------------------------------------
  To find other possible module matches execute:

      $ module -r spider '.*spark.*'

----------------------------------------------------------------------------
  For detailed information about a specific "spark" package (including how to load the modules) use the module's full name. Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider spark/3.2.1
----------------------------------------------------------------------------
[mkandes@login02 ~]$ module spider spark/3.4.0

----------------------------------------------------------------------------
  spark/3.4.0: spark/3.4.0/sntnkcq
----------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "spark/3.4.0/sntnkcq" module is available to load.

      cpu/0.17.3b  gcc/10.2.0/npcyll4
 
    Help:
      Apache Spark is a fast and general engine for large-scale data
      processing.


 

[mkandes@login02 ~]$
```

**Comment by mkandes** [comment]
But we can easily expose the latest version of hadoop from spark ...

```
[mkandes@login02 ~]$ . /cm/shared/apps/spack/0.17.3/cpu/b/share/spack/setup-env.sh 
[mkandes@login02 ~]$ spack find -lvdp spark
==> 1 installed package
-- linux-rocky8-zen2 / gcc@10.2.0 -------------------------------
sntnkcq spark@3.4.0+hadoop  /cm/shared/apps/spack/0.17.3/cpu/b/opt/spack/linux-rocky8-zen2/gcc-10.2.0/spark-3.4.0-sntnkcqkor2zmovkogcjf5qivzxdul5v
bfyu354     hadoop@3.3.0               /cm/shared/apps/spack/0.17.3/cpu/b/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hadoop-3.3.0-bfyu354o4z5trshyxr6zkg463zdoat2f
27cv2ps         openjdk@11.0.12_7      /cm/shared/apps/spack/0.17.3/cpu/b/opt/spack/linux-rocky8-zen2/gcc-10.2.0/openjdk-11.0.12_7-27cv2psb6xthjbwmjlx53otdbjxch6wg

[mkandes@login02 ~]$
```
... by directly modifying the `modules.yaml` whitelist.

```
[mkandes@login02 ~]$ cat /cm/shared/apps/spack/0.17.3/cpu/b/etc/spack/modules.yaml 
modules:
  default:
    enable::
      - lmod
    lmod:
      core_compilers:
        - 'gcc@8.5.0'
      hierarchy:
        - mpi
      hash_length: 0
      blacklist_implicits: true
      whitelist: ['py-jupyter-core']
      naming_scheme: '{name}/{version}/{hash:7}'
      projections:
        all: '{name}/{version}/{hash:7}'
      all:
        suffixes:
          '+openmp': omp
          'threads=openmp': omp
          '+ipl64': i64
        environment:
          set:
            '{name}HOME': '{prefix}'
      intel:
        environment:
          set:
            INTEL_LICENSE_FILE: '40000@elprado.sdsc.edu:40200@elprado.sdsc.edu'
      petsc:
        suffixes:
          '+complex': cmplx
      slepc:
        suffixes:
          '^petsc +complex': cmplx
      ^python:
        autoload: 'direct'
      ^ucx:
        autoload: 'direct'
[mkandes@login02 ~]$
```
This type of simple change is typically safe enough to perform a quick hotfix directly on the production instance and then committing the change back directly to the sdsc/spack repo without having to submit the change as a pull request.
